name: Build Snake (Debug)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/android-debug.yml"
      - "app/**"
      - "build.gradle"
      - "settings.gradle"
      - "gradle.properties"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # --- Génération des fichiers projet si besoin ---
      # (si ton projet est déjà commité, tu peux supprimer ce bloc)
      - name: Generate project files (Snake v1.1)
        run: |
          set -e
          mkdir -p app/src/main/java/com/example/snake
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values
          echo '<?xml version="1.0" encoding="utf-8"?>\n<manifest xmlns:android="http://schemas.android.com/apk/res/android"\n    package="com.example.snake">\n    <application\n        android:allowBackup="true"\n        android:label="Snake"\n        android:supportsRtl="true"\n        android:theme="@style/Theme.AppCompat.DayNight.NoActionBar">\n        <activity android:name=".MainActivity">\n            <intent-filter>\n                <action android:name="android.intent.action.MAIN" />\n                <category android:name="android.intent.category.LAUNCHER" />\n            </intent-filter>\n        </activity>\n    </application>\n</manifest>' > app/src/main/AndroidManifest.xml

      # --------- FIX: utilisation de Gradle local ---------
      - name: Download Gradle 8.7
        run: |
          set -e
          curl -L --retry 5 --retry-delay 3 -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          ./gradle-8.7/bin/gradle -v

      # --------- Cache Gradle pour accélérer les builds ---------
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/settings.gradle*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build Debug APK (using local Gradle)
        env:
          GRADLE_USER_HOME: ~/.gradle
        run: |
          ./gradle-8.7/bin/gradle --no-daemon --stacktrace assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error